name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install bundler
      run: gem install bundler
    - name: Bundle install
      run: bundle install
    - name: Build
      run: ./gradlew assembleRelease
    - name: Test
      run: ./gradlew testRelease
    - name: ktlint
      run: ./gradlew ktlintCheck
    - name: detekt
      run: ./gradlew detekt
    - name: Android Lint
      run: ./gradlew :app:lintRelease
    - name: Danger
      run: bundle exec danger
