name: Build and check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build debug
      run: ./gradlew assembleDebug

    - name: Check
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        ./gradlew testDebug
        ./gradlew ktlintCheck
        ./gradlew detekt
        ./gradlew :app:lintDebug

    - name: Setup ruby
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install bundler
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        GEM_BUNDLER_VERSION=$(grep -A1 -E -i -w '(BUNDLED WITH){1,1}' .ci/Gemfile.lock | grep -E -i -w "[0-9\.]{1,}" | xargs)
        gem install bundler -v=$GEM_BUNDLER_VERSION --force

    - name: Run danger for static analysis
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle install --gemfile=.ci/Gemfile
        bundle exec --gemfile=.ci/Gemfile danger --dangerfile=".ci/danger/static_analysis.danger"

    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ (github.event_name == 'pull_request' && 'build-outputs') || 'latest-apk' }}
        path: app/build/outputs/apk/**/*.apk
