name: Run upgrade dependencies
on:
  repository_dispatch:
  schedule:
    - cron:  '0 3 * * 0'
jobs:
  upgrade_dependencies:
    if: (github.event_name == 'repository_dispatch' && github.event.action == 'upgrade_dependencies') || (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run upgrade dependencies
        run: ./gradlew upgradeDependencies
        env:
          gitHubWriteToken: ${{ secrets.GITHUB_TOKEN }}